config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/documents/:id/download", to: "documents#download", as: "document_download"
  get "/documents/:id/preview/", to: "documents#preview", as: "document_preview"

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :index]

  resources :clients, only: [:index, :show, :new, :create] do
    resources :documents, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :document
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :client
  has_one_attached :file
  TAX_NAME = ["IVA", "SIJP", "SICORE", "ING. BRUTOS", "GANANCIAS"]
  AGENCY_NAME = ["RENTAS", "AFIP"]

  include PgSearch::Model

  pg_search_scope :search_by_name_and_agency,
                  against: [ :description, :agency, :tax_name, :date ],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show]
  before_action :set_documents, only: [:show]

  def index
    @clients = Client.all
  end

  def show
    if params[:search]
      @documents = Document.search_by_name_and_agency(params[:search]).where(client: @client)
    else
      @documents = Document.where(client: @client)
    end

    if params[:query]
      @documents = @documents.where(tax_name: params[:query]).where(client: @client)
    end

    # the agency: in line 22 is related with the column in the schema --> to see if agency is present in the params
    # So i want to show the documents where where params and agency(schema) are equals. !!??
    if params[:agency_filter]
      @documents = @documents.where(agency: params[:agency_filter]).where(client: @client)
    end
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

    if @client.save!
      redirect_to clients_path
    else
      render :new
    end
  end

  private

  def set_documents
    @documents = Document.where(client: @client)
  end

  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:name, :cuit, :domicilio)
  end
end

app/controllers/documents_controller.rb
require 'open-uri'

class DocumentsController < ApplicationController
  before_action :set_client, only: [:new]
  def index
    @documents = Document.all
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)

    if @document.save!
      redirect_to clients_path
    else
      render :new
    end
  end

  def download
    @document = Document.find(params[:id])
    pdf = Prawn::Document.new

    params[:images][0..-2].each_with_index do |img, index|
      doc_image = URI.open(img)
      pdf.image doc_image, fit: [700, 700], position: :center, position: :center
      # pdf.start_new_page unless params[:images][index + 1].nil?
    end
    send_data(pdf.render, filename: "#{@document.agency}_#{@document.tax_name}_#{@document.description}", type: "application/pdf")
  end

  def preview
    @document = Document.find(params[:id])
    pdf = Prawn::Document.new

    params[:images][0..-2].each_with_index do |img, index|
      doc_image = URI.open(img)
      pdf.image doc_image, fit: [700, 700], position: :center, position: :center
      # pdf.start_new_page unless params[:images][index + 1].nil?
    end

    # pdf.image doc_image, fit: [800, 800], position: :center, position: :center
    send_data(pdf.render, filename: "#{@document.agency}_#{@document.tax_name}_#{@document.description}", type: "application/pdf", disposition: "inline")
  end

  private

  def set_client
    @client = Client.find(params[:client_id])
  end

  def document_params
    params.require(:document).permit(:client_id, :description, :agency, :tax_name, :date, :file)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @users = User.find(params[:id])
    @clients = Client.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/index.html.erb
<% @clients.each do |client| %>
  <%= link_to client %>
<% end %>

app/views/clients/new.html.erb
<div class="container form">
  <h2 class= "form">Cargar los datos de nuevos clientes</h2>
  <%= simple_form_for [@client] do |f| %>
    <%= f.input :name, label: "Nombre del Cliente" %>
    <%= f.input :cuit, label: "Numero de C.U.I.T" %>
    <%= f.input :domicilio, label: "Domicilio" %>
    <%= f.submit %>
  <% end %>
</div>

app/views/clients/show.html.erb
<div class="remove-underline">
  <%= link_to "Volver a todos los clientes", user_path %>
</div>

<span>
  <h2 class="client-title">Archivos de <%= @client.name %></h2>
</span>

<span class="form">
  <%= form_with url: client_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :search,
      params[:search],
      class: "form-control",
      placeholder: "Buscar por documentos"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
</span>

<div class="new-file">
  <%= link_to "Añadir un archivo", new_client_document_path(@client), class: "btn btn-primary"%>
</div>

<div class="files-section">
<div class="filters">
    <p>Filtrar por agencia</p>
   <% Document::TAX_NAME.each do |tax| %>
   <% if params[:query]&.include?(tax)%>
      <%= link_to tax, client_path(@client, query: params[:query] - [tax])%>
    <% else %>
      <%# link_to client_path(@client --> show page of the client %>
      <%# query: params[:query] -- checking if params query exist? true/false %>
      <%# if they exist --> add the new filter params[:query] + [tax] to the params hash --> true condition %>
      <%# if does not exist --> create the new params query with the first argunemt [tax ] --> false condition%>
      <%# link_to tax -->  %>
    <%= link_to tax, client_path(@client, query: params[:query] ? params[:query] + [tax] : [tax])%>
     <% end %>
   <% end %>

  <p>Filtrar por impuesto</p>
   <% Document::AGENCY_NAME.each do |name| %>
   <% if params[:agency_filter]&.include?(name)%>
        <%= link_to name, client_path(@client, agency_filter: params[:agency_filter] - [name])%>
    <% else %>
        <%= link_to name, client_path(@client, agency_filter: params[:agency_filter] ? params[:agency_filter] + [name] : [name])%>
     <% end %>
   <% end %>
</div>

<div>
<div data-controller="modal" class="doc-grid">
  <% @documents.each do |doc| %>
		<div>
			<div class="d-none modal" data-modal-target="modal">
				<div class="modal-inner" data-action="click->modal#close">
				</div>

				<div class="position-absolute">
					<div data-modal-target="modalImgShell" class="h-100 w-100 d-flex flex-column align-items-end justify-content-center">
						<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
							<path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
						</svg>
					</div>
				</div>
			</div>

      <% if doc.file.attached? %>
        <% if doc.file.representable? %>
					<% path = cl_image_path(doc.file.key) + ".jpg" %>
					<% index = path.index("/upload/") + path["/upload/"].size %>

					<% url = URI.parse(path) %>
					<%# <% req = Net::HTTP.new(url.host, url.port) %>
					<%# <% req.use_ssl = true %>
					<%# <% res = req.request_head(url.path) %>
					<% images = [] %>
					<% counter = 1 %>
					<% http = Net::HTTP.new(url.host, url.port) %>
					<% while http.head(url.request_uri).code == '200' %>
						<% url_pg = path.insert(index, "pg_#{counter}/") %>
						<% url = URI.parse(url_pg) %>
						<% http = Net::HTTP.new(url.host, url.port) %>
						<%# <% req = Net::HTTP.new(url.host, url.port) %>
						<%# <% req.use_ssl = true %>
						<%# <% res = req.request_head(url.path) %>

						<%# <% Net::HTTP.start(url.host, url.port) do |http| %>
							<%# <% raise %>
							<%# <% break unless http.head(url.request_uri).code == '200' %>
						<%# <% end %>
						<% new_url = url_pg.dup %>
						<% images << new_url %>
						<% path.gsub!(/pg_\d\//, "") %>
						<% counter += 1 %>
					<% end %>

					<img src="<%= cl_image_path(doc.file.key) %>.jpg" class="grid-item" data-action="click->modal#openPdf" data-view="<%= cl_image_path(doc.file.key) %>.pdf" data-images="<%= images %>">


        <% else %>
          <%= cl_image_tag(doc.file.key, class: "grid-item", data: {action: "click->modal#open", view: cl_image_path(doc.file.key)}) %>
        <% end %>
      <% end %>


		<p><%= doc.description %></p>
    
			<%= link_to "Download", document_download_path(doc, images: images), target: "_blank" %>
			<%= link_to "Preview", document_preview_path(doc, images: images), target: "_blank" %>

		</div>
  <% end %>
</div>
</div>
</div>

<%# parse data-images in JS controller %>
<%# use JS to insert bootstrap carousel %>

app/views/documents/new.html.erb
<div class="container form">
  <h2 class= "form">Cargar los nuevos documentos</h2>
  <%= simple_form_for [@client, @document] do |f| %>
    <%= f.association :client %>
    <%= f.input :description, label: "Descripción" %>
    <%= f.input :agency, collection: Document::AGENCY_NAME, label: "Oficina de gobierno" %>
    <%= f.input :tax_name, collection: Document::TAX_NAME, label: "Tipo de impuesto" %>
    <%= f.input :date, as: :date, order: [:month, :year], label: "Fecha" %>
    <%= f.input :file, as: :file, label: "Adjuntar archivo PDF" %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArchivosDigitales</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <h1>Gestor Contable</h1>
  <h2>Archivos contables ordenados de una manera mas simple y eficiente</h2>
</div>
<div class="container list">
  <ul>
    <li>Eficiencia</li>
    <li>Orden</li>
    <li>Simplicidad</li>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Here we have a control page for the user </h1>
<h2> Welcome <%=current_user.name%></h2>

<h3>Here we are going to have all the customers and we can access to each of them</h3>
<%= link_to 'Crear un nuevo cliente', '/clients/new' %>

<% @clients.each do |client| %>
  <%= link_to client.name, client_path(client) %>
<% end %>